version: '3.3'

services:
  prometheus:
    image: prom/prometheus:v2.6.0
    container_name: prometheus_on_dockercompose
    ports:
      - "9090:9090"
    volumes:
      - ./svr/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./svr/prometheus:/prometheus
    restart: always
